install:
  - wget http://downloads.sourceforge.net/project/x10/x10/2.5.4/x10-2.5.4_linux_x86_64.tgz
  - mkdir -p x10
  - tar xvzf x10-2.5.4_linux_x86_64.tgz -C x10
before_script:
  - export PATH=$PWD/x10/bin:$PATH
script:
  - test/build_run_test.sh

